#!/usr/bin/env bash
# This script display 
# The exact format must be:
# OCCURENCE_NUMBER IP HTTP_CODE
# In list format
# Ordered from the greatest to the lowest number of occurrences

awk '{print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
